---
platform: linux

image: docker:///windkithk/leofs_deploy

# image_resource:
#   type: docker-image
#   source:
#     repository: windkithk/leofs_deploy

params:
  ANSIBLE_INVENTORY:
  ANSIBLE_KEY:
  LEOFS_GW_HOST:
  BUCKETS:

inputs:
- name: leofs_concourse
- name: leofs_ansible
- name: leofs_src

run:
  path: leofs_concourse/scripts/deploy_leofs.sh
